plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.0.cjs

packageExtensions:
  auto@*:
    dependencies:
      "@auto-it/npm": "*"
      "@auto-it/first-time-contributor": "*"
      "@auto-it/all-contributors": "*"
